name: data
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch: null
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.basketball-reference.com/leagues/NBA_2022_per_game.html
          downloaded_filename: per_game_players.html
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.basketball-reference.com/contracts/players.html
          downloaded_filename: players.html
          postprocess: ./postprocess.ts
